

============== Preparing virtualenv ==============
________________________________________
Shell: python --version
Python 3.8.5

Shell: Exit OK
----------------------------------------

________________________________________
Shell: python -m virtualenv --version
virtualenv 20.4.6 from C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\site-packages\virtualenv\__init__.py

Shell: Exit OK
----------------------------------------

________________________________________
Shell: env\Scripts\python.exe --version
Python 3.8.5

Shell: Exit OK
----------------------------------------


============== Install requirements ==============
________________________________________
Shell: env\Scripts\pip.exe install -U -r installer/requirements.txt
Ignoring pync: markers 'sys_platform == "darwin"' don't match your environment
Collecting akinator.py
  Using cached akinator.py-4.1.0-py3-none-any.whl (19 kB)
Collecting archey4==4.6.0.post1
  Using cached archey4-4.6.0.post1-py3-none-any.whl (14 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting distro
  Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting flake8
  Using cached flake8-3.9.2-py2.py3-none-any.whl (73 kB)
Collecting forex-python
  Using cached forex-python-1.5.tar.gz (7.5 kB)
Collecting geopy
  Using cached geopy-2.1.0-py3-none-any.whl (112 kB)
Collecting gitpython
  Using cached GitPython-3.1.17-py3-none-any.whl (166 kB)
Collecting googletrans
  Using cached googletrans-3.0.0.tar.gz (17 kB)
Collecting IMDbPY
  Using cached IMDbPY-2021.4.18-py3-none-any.whl (298 kB)
Collecting mock
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting nltk
  Using cached nltk-3.6.2-py3-none-any.whl (1.5 MB)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
Collecting pdfkit
  Using cached pdfkit-0.6.1-py3-none-any.whl (12 kB)
Collecting pick
  Using cached pick-1.0.0-py2.py3-none-any.whl (5.5 kB)
Collecting pluginmanager
  Using cached pluginmanager-0.4.1-py2.py3-none-any.whl (26 kB)
Collecting psutil
  Using cached psutil-5.8.0-cp38-cp38-win_amd64.whl (245 kB)
Collecting pycricbuzz
  Using cached pycricbuzz-2.4-py2.py3-none-any.whl (10 kB)
Collecting pydoc-markdown
  Using cached pydoc_markdown-3.11.0-py3-none-any.whl (57 kB)
Collecting pydub
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting pyjokes
  Using cached pyjokes-0.6.0-py2.py3-none-any.whl (26 kB)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting pyreadline
  Using cached pyreadline-2.1.zip (109 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytimeparse
  Using cached pytimeparse-1.1.8-py2.py3-none-any.whl (10.0 kB)
Collecting pyttsx3==2.71
  Using cached pyttsx3-2.71-py3-none-any.whl (39 kB)
Collecting pywin32
  Using cached pywin32-300-cp38-cp38-win_amd64.whl (9.3 MB)
Collecting random-word
  Using cached Random_Word-1.0.7-py3-none-any.whl (8.0 kB)
Collecting requests[security]
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting speedtest-cli
  Using cached speedtest_cli-2.1.3-py2.py3-none-any.whl (23 kB)
Collecting sympy
  Downloading sympy-1.8-py3-none-any.whl (6.1 MB)
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting termdown
  Downloading termdown-1.17.0-py3-none-any.whl (21 kB)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.5.2.52-cp38-cp38-win_amd64.whl (34.6 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__
    super().__init__(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\cli\progress_bars.py", line 152, in iter
    for x in it:
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_internal\network\utils.py", line 62, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\AKASH\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\AKASH\PycharmProjects\Jarvis\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Shell: Exit FAIL Command 'env\Scripts\pip.exe install -U -r installer/requirements.txt' returned non-zero exit status 2.
----------------------------------------

Installation failed


FATAL!
